version: '3.8'

services:
  larissag:
    image: ghcr.io/larissaguaman1/landingquintoa:1.0.0
    networks:
      - traefik-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # HTTP
        - "traefik.http.routers.larissag.rule=Host(`larissag.byronrm.com`)"
        - "traefik.http.routers.larissag.entrypoints=http"
        - "traefik.http.routers.larissag.middlewares=larissag-https-redirect"

        # Redirección a HTTPS
        - "traefik.http.middlewares.larissag-https-redirect.redirectscheme.scheme=https"

        # HTTPS
        - "traefik.http.routers.larissag-secure.rule=Host(`larissag.byronrm.com`)"
        - "traefik.http.routers.larissag-secure.entrypoints=https"
        - "traefik.http.routers.larissag-secure.tls=true"
        - "traefik.http.routers.larissag-secure.tls.certresolver=http"
        - "traefik.http.routers.larissag-secure.service=larissag"

        # Puerto interno de Flask
        - "traefik.http.services.larissag.loadbalancer.server.port=5000"

        # Red de Traefik
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true